/*
Write a java program using LinkedList for bucketlist.
On execution program shows following menu.
until user type/select EXIT option, program should keeps showing the menu.
Menu:
1. Add item from bucketlist.
	i. Add at the start of the list
	ii. Add at the end of the list.
	iii. Add at the user selected place[If user enters invalid position, print error on screen and continue showing main menu.].
2. Delete item from bucketlist.
	i. Delete first item in the list.
	ii. Delete last item in the list.
	iii. Delete at the user selected place[If user enters invalid position, print error on screen and continue showing main menu.].
3. Print Bucketlist.
	i. Show items in bucketlist if items present.
	ii. If bucketlist is empty, print "Aha..Your bucketlist is empty. Add item to it.".
*/

class BucketListDemo
{
	public static void main(String[] args)
	{
		
	}
}

class BucketList
{
	
}
